(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (if (prime? n)
     (report-prime (- (runtime) start-time))))
(define (report-prime elapsed-time)
  (display "...is prime elapsed time: ")
  (display elapsed-time))

(define (prime? n)
  (= n (smallest-divisor n)))
(define (smallest-divisor n) (find-divisor n 2))
(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
	((divides? test-divisor n) test-divisor)
	(else (find-divisor n (+ test-divisor 1)))))
(define (divides? a b) (= (remainder b a) 0))

(define (search-for-primes start end)
  (cond ((< end start) (display "done"))
	(else 
	  (timed-prime-test start)
	  (search-for-primes (+ start 2) end)
	  )
	)
  ) 
  
; (search-for-primes 1001 9999)
; (search-for-primes 10001 99999)
; (search-for-primes 100001 999999)
(search-for-primes 1000001 1000100)
